import type { PortfolioData } from './types.js';

export const portfolioData: PortfolioData = {
  profile: {
    name: 'Shyad Musthafa A',
    designation: 'Software Engineer',
    tagline: 'Full Stack Developer | Backend Developer',
    introduction:
      'Software Engineer with hands-on experience in web application development, specializing in Angular, PHP, Laravel, SQL, and MS SQL. Proven track record in developing enterprise-level applications including HR Management Systems, Asset Management, Rental Systems, and Agreement Management platforms.',
    avatar: 'img/shyad profile.jpg',
    resumeUrl: 'img/Shyad ATS.pdf',
    email: 'shyadmusthafa001@gmail.com',
    phone: '+91 93841 48769',
    location: 'Karur, Tamil Nadu, India',
    availability: 'Available for Freelance',
    social: [
      { platform: 'LinkedIn', url: 'https://linkedin.com/in/shyad-musthafa-a-9931031b6', icon: 'bi-linkedin' },
      { platform: 'GitHub', url: 'https://github.com', icon: 'bi-github' },
      { platform: 'Email', url: 'mailto:shyadmusthafa001@gmail.com', icon: 'bi-envelope' },
    ],
  },
  stats: [
    { label: 'Years Experience', value: 3, suffix: '+', icon: 'bi-briefcase' },
    { label: 'Enterprise Projects', value: 6, suffix: '+', icon: 'bi-folder-check' },
    { label: 'Systems Delivered', value: 4, suffix: '', icon: 'bi-building' },
    { label: 'CGPA (B.E.)', value: 8, suffix: '.3', icon: 'bi-mortarboard' },
  ],
  about: {
    summary:
      'Software Engineer with hands-on experience in web application development, specializing in Angular, PHP, Laravel, SQL, and MS SQL. Proven track record in developing enterprise-level applications including HR Management Systems, Asset Management, Rental Systems, and Agreement Management platforms. Expertise in full-stack development, API integration, payment gateway implementation, and automated workflow systems. Strong background in database design, complex query optimization, and building scalable solutions that improve business processes.',
    journey: [
      {
        period: 'Oct 2022 – Present',
        title: 'Software Engineer',
        subtitle: 'Chettinad Groups, Chennai',
        description:
          'Full-time role building enterprise applications across HR, Asset, Rental, and Agreement management domains.',
        highlights: [
          'Integrated CC Avenue payment gateway & OTP authentication',
          'Built Django agreement management with approval workflows',
          'Optimized MS SQL queries for port operations platform',
        ],
      },
      {
        period: '2019 – 2022',
        title: 'B.E. Computer Science Engineering',
        subtitle: 'Chettinad College of Engineering & Technology, Karur',
        description: 'Focused on software engineering fundamentals, databases, and web technologies. CGPA: 8.3/10.0',
        highlights: ['Anna University affiliated program', 'Capstone in enterprise web development'],
      },
      {
        period: '2016 – 2019',
        title: 'Diploma in Computer Science Engineering',
        subtitle: 'Government Polytechnic College, Karur',
        description: 'Foundation in programming, databases, and application development. CGPA: 7.8/10.0',
      },
    ],
    education: [
      {
        period: 'Jun 2019 – Apr 2022',
        title: 'B.E. in Computer Science Engineering',
        subtitle: 'Chettinad College of Engineering & Technology, Karur',
        description: 'Anna University · CGPA: 8.3/10.0',
      },
      {
        period: 'Jun 2016 – Apr 2019',
        title: 'Diploma in Computer Science Engineering',
        subtitle: 'Government Polytechnic College, Karur',
        description: 'DOTE · CGPA: 7.8/10.0',
      },
      {
        period: 'Jun 2015 – Apr 2016',
        title: 'SSLC (Secondary School)',
        subtitle: 'Vivekananda Higher Secondary School, Karur',
        description: 'State Board · CGPA: 7.6/10.0',
      },
    ],
    personalInfo: [
      { label: 'Name', value: 'Shyad Musthafa A', icon: 'bi-person' },
      { label: 'Location', value: 'Karur, Tamil Nadu, India', icon: 'bi-geo-alt' },
      { label: 'Experience', value: '3+ Years', icon: 'bi-clock-history' },
      { label: 'Freelance', value: 'Available', icon: 'bi-check-circle' },
      { label: 'Email', value: 'shyadmusthafa001@gmail.com', icon: 'bi-envelope' },
      { label: 'Phone', value: '+91 93841 48769', icon: 'bi-telephone' },
      { label: 'AI Tools', value: 'Cursor AI, ChatGPT, Claude', icon: 'bi-robot' },
    ],
    achievements: [
      'Delivered 6+ enterprise applications for Chettinad Groups',
      'Integrated CC Avenue payment gateway across rental billing systems',
      'Built automated payroll processing with biometric attendance integration',
      'Developed XML export module for Tally accounting integration',
      'Implemented OTP-based tenant authentication for rental management',
      'Optimized MS SQL queries improving port operations platform performance',
      'Leverages Cursor AI, ChatGPT, and Claude for faster development, debugging, and code optimization',
    ],
  },
  skillCategories: [
    {
      id: 'frontend',
      name: 'Frontend',
      icon: 'bi-window-desktop',
      skills: [
        { name: 'Angular', level: 85, icon: 'bi-code-slash' },
        { name: 'TypeScript', level: 80, icon: 'bi-braces' },
        { name: 'JavaScript', level: 90, icon: 'bi-filetype-js' },
        { name: 'HTML / CSS', level: 95, icon: 'bi-palette' },
      ],
    },
    {
      id: 'backend',
      name: 'Backend',
      icon: 'bi-server',
      skills: [
        { name: 'PHP / Laravel', level: 92, icon: 'bi-hdd-network' },
        { name: 'Python / Django', level: 80, icon: 'bi-filetype-py' },
        { name: 'REST API Development', level: 88, icon: 'bi-diagram-3' },
        { name: 'Ajax', level: 85, icon: 'bi-arrow-left-right' },
      ],
    },
    {
      id: 'database',
      name: 'Database',
      icon: 'bi-database',
      skills: [
        { name: 'MS SQL Server', level: 90, icon: 'bi-database-fill' },
        { name: 'MySQL', level: 88, icon: 'bi-collection' },
        { name: 'SQL Query Optimization', level: 90, icon: 'bi-search' },
        { name: 'HeidiSQL', level: 85, icon: 'bi-table' },
      ],
    },
    {
      id: 'tools',
      name: 'Dev Tools',
      icon: 'bi-gear-wide-connected',
      skills: [
        { name: 'Git / GitHub', level: 85, icon: 'bi-git' },
        { name: 'VS Code', level: 95, icon: 'bi-code-square' },
        { name: 'Cron Jobs', level: 88, icon: 'bi-clock' },
        { name: 'WAMP / XAMPP', level: 90, icon: 'bi-pc-display' },
      ],
    },
    {
      id: 'integrations',
      name: 'Integrations',
      icon: 'bi-plug',
      skills: [
        { name: 'CC Avenue Payment Gateway', level: 88, icon: 'bi-credit-card' },
        { name: 'OTP Authentication', level: 85, icon: 'bi-shield-lock' },
        { name: 'Excel / XML Processing', level: 82, icon: 'bi-file-earmark-spreadsheet' },
        { name: 'Tally Integration', level: 80, icon: 'bi-calculator' },
      ],
    },
    {
      id: 'ai-tools',
      name: 'AI Tools',
      icon: 'bi-robot',
      skills: [
        { name: 'Cursor AI', level: 90, icon: 'bi-cursor' },
        { name: 'ChatGPT', level: 88, icon: 'bi-chat-dots' },
        { name: 'Claude', level: 88, icon: 'bi-stars' },
      ],
    },
  ],
  experience: [
    {
      id: 'exp1',
      period: 'Oct 2022 – Present',
      company: 'Chettinad Groups',
      role: 'Software Engineer',
      location: 'Chennai, Tamil Nadu',
      description:
        'Hands-on full-stack web development using Angular, PHP, Laravel, SQL, and MS SQL on enterprise applications including HR Management, Asset Management, Rental, and Agreement Management systems.',
      responsibilities: [
        'Implemented backend solutions using PHP and Laravel for API handling, database queries, and complex business logic',
        'Developed and optimized Angular applications with dynamic forms, multi-select dropdowns, Material tables, and responsive UI',
        'Designed and optimized complex SQL queries for reporting, payroll processing, and multi-source data integration',
        'Integrated CC Avenue payment gateway, OTP-based authentication, and automated workflows using cron jobs',
        'Built Django-based applications for agreement management with approval workflows and automated email notifications',
        'Collaborated with cross-functional teams for requirement analysis, system design, and feature implementation',
        'Provided technical support to end-users and resolved production issues efficiently',
      ],
      achievements: [
        'Streamlined workflows for asset management, HR time management, payroll processing, and rental systems',
        'Built attendance-based salary calculation using Biometric, Department, and Government (NMC) data',
        'Created real-time operational dashboards for port management reducing manual monitoring efforts',
        'Implemented role-based access control and secure API integrations for port operations',
      ],
      projects: [
        'HR Management System',
        'PGHRIS',
        'Asset Management',
        'Rental Management',
        'Agreement Management',
        'Chettinad PortBird',
      ],
    },
  ],
  projects: [
    {
      id: 'p1',
      title: 'Human Resource Management System',
      description:
        'Employee lifecycle management including onboarding, attendance, payroll, and separation. Time management modules for leave, shifts, and holidays with automated payroll processing, payslip generation, and reports.',
      image: 'hris.png',
      category: 'hr',
      tags: ['Angular', 'PHP Laravel', 'SQL', 'HeidiSQL'],
      liveUrl: 'https://hris.chettinad.com/',
      featured: true,
    },
    {
      id: 'p2',
      title: 'PGHRIS (HR & Payroll Management)',
      description:
        'Employee and student payroll system with onboarding, stipend processing, and leave workflows. Attendance-based salary calculation using Biometric, Department, and Government (NMC) data with lowest attendance count logic.',
      image: 'pghris.png',
      category: 'hr',
      tags: ['Angular', 'PHP Laravel', 'SQL', 'Payroll'],
      liveUrl: 'https://stuhris.chettinad.com',
      featured: true,
    },
    {
      id: 'p3',
      title: 'Asset Management System',
      description:
        'Asset purchase, allocation, transfer, and employee-wise tracking. Automated product imports via cron jobs, asset clearance workflow during employee relieving, and XML export module for Tally accounting integration.',
     image: 'Asset_mgt_project.png',
      category: 'asset',
      tags: ['Angular', 'Laravel', 'Cron Jobs', 'XML', 'Tally'],
      liveUrl: 'http://asset.care.edu.in/',
      featured: true,
    },
    {
      id: 'p4',
      title: 'Rental Management System',
      description:
        'Tenant onboarding with OTP-based authentication, building and room management with fixed rent configuration, automated monthly billing with GST and CC Avenue payment integration, and tenant dashboard for bills and payment history.',
     image: 'Rental Management System.png',
      category: 'rental',
      tags: ['PHP Laravel', 'CC Avenue', 'OTP Auth', 'GST Billing'],
      liveUrl: 'https://rental.chettinad.com:74/',
      featured: false,
    },
    {
      id: 'p5',
      title: 'Agreement Management System',
      description:
        'Django-based system for SPO, CFA, and Transport agreements with data entry, attachments, approval workflows, and automated email notifications for agreement movement tracking.',
      image: 'aggrement.png',
      category: 'agreement',
      tags: ['Python', 'Django', 'SQL', 'Workflows'],
      liveUrl: 'http://agreement.chettinad.com:177/',
      featured: false,
    },
    {
      id: 'p6',
      title: 'Chettinad PortBird',
      description:
        'Port operations platform with vessel scheduling, cargo tracking, billing, gate pass management, and marine services. Real-time operational dashboards, role-based access control, and optimized MS SQL backend services.',
      image: 'img/Dashboard _ Chettinad PortBird.png',
      category: 'port',
      tags: ['PHP', 'Ajax', 'MS SQL Server', 'Dashboards'],
      liveUrl: 'https://portbird.chettinad.com:66/',
      featured: true,
    },
  ],
  certifications: [
    {
      id: 'c1',
      title: 'B.E. Computer Science Engineering',
      provider: 'Anna University — CCET Karur',
      date: '2022',
      image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400&h=280&fit=crop',
      credentialUrl: '#',
    },
    {
      id: 'c2',
      title: 'Diploma in Computer Science Engineering',
      provider: 'DOTE — Government Polytechnic College, Karur',
      date: '2019',
      image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&h=280&fit=crop',
      credentialUrl: '#',
    },
    {
      id: 'c3',
      title: 'SSLC — Science Stream',
      provider: 'Vivekananda Higher Secondary School, Karur',
      date: '2016',
      image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=280&fit=crop',
      credentialUrl: '#',
    },
  ],
  services: [
    {
      id: 's1',
      title: 'Full Stack Web Development',
      description: 'End-to-end web applications using Angular, PHP, Laravel, and SQL for enterprise business needs.',
      icon: 'bi-code-square',
      features: ['Angular frontends', 'Laravel REST APIs', 'Responsive UI components', 'Material tables & forms'],
    },
    {
      id: 's2',
      title: 'Backend & API Development',
      description: 'Robust backend solutions with complex business logic, database queries, and REST API integrations.',
      icon: 'bi-server',
      features: ['PHP / Laravel backends', 'Django applications', 'REST API design', 'Cron job automation'],
    },
    {
      id: 's3',
      title: 'Database Design & Optimization',
      description: 'MS SQL and MySQL database design, complex query optimization, and reporting solutions.',
      icon: 'bi-database',
      features: ['Query optimization', 'Payroll & reporting SQL', 'Multi-source data integration', 'HeidiSQL administration'],
    },
    {
      id: 's4',
      title: 'Payment & Integration Services',
      description: 'Payment gateway integration, OTP authentication, and third-party system connectivity.',
      icon: 'bi-credit-card',
      features: ['CC Avenue integration', 'OTP authentication', 'Tally XML export', 'Excel/XML processing'],
    },
  ],
  blog: [
    {
      id: 'b1',
      title: 'Building Scalable HR Payroll Systems with Laravel',
      excerpt: 'How to design attendance-based salary calculation using biometric, department, and government data sources.',
      category: 'Backend',
      date: 'Mar 10, 2025',
      readTime: '7 min read',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&h=350&fit=crop',
      featured: true,
    },
    {
      id: 'b2',
      title: 'Angular Material Tables for Enterprise Dashboards',
      excerpt: 'Best practices for dynamic forms, multi-select dropdowns, and responsive data tables in Angular applications.',
      category: 'Frontend',
      date: 'Feb 20, 2025',
      readTime: '6 min read',
      image: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=600&h=350&fit=crop',
      featured: true,
    },
    {
      id: 'b3',
      title: 'Integrating CC Avenue Payment Gateway in Laravel',
      excerpt: 'Step-by-step guide to implementing secure payment flows with automated billing and GST calculations.',
      category: 'Backend',
      date: 'Feb 5, 2025',
      readTime: '8 min read',
      image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&h=350&fit=crop',
      featured: false,
    },
    {
      id: 'b4',
      title: 'Optimizing MS SQL Queries for Reporting Systems',
      excerpt: 'Techniques for complex query optimization in enterprise reporting, payroll, and multi-source data integration.',
      category: 'Database',
      date: 'Jan 15, 2025',
      readTime: '9 min read',
      image: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&h=350&fit=crop',
      featured: false,
    },
  ],
  contact: {
    mapEmbed:
      'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d125301.44567226247!2d78.04346031640625!3d10.960103000000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3baa2f102dde86c3%3A0xf49f5a8584c5b5f8!2sKarur%2C%20Tamil%20Nadu!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin',
    formEndpoint: '#',
  },
  analytics: {
    pageViews: 8420,
    uniqueVisitors: 3150,
    avgSession: '3m 18s',
    bounceRate: 32.4,
    topProjects: [
      { name: 'HRIS', views: 2100 },
      { name: 'Asset Mgmt', views: 1850 },
      { name: 'PortBird', views: 1420 },
      { name: 'Rental', views: 980 },
    ],
    trafficSources: [
      { source: 'Direct', percentage: 38 },
      { source: 'LinkedIn', percentage: 35 },
      { source: 'Company Portal', percentage: 17 },
      { source: 'Google', percentage: 10 },
    ],
    monthlyViews: [420, 510, 580, 640, 720, 810, 890, 950, 1020, 1100, 1180, 1250],
  },
};
